version: '3'

services:
  
  fhir-connect:
    build: mirth-connect
    volumes:
      - "./mirth-connect/mirth.properties:/opt/mirth-connect/conf/mirth.properties:ro"
      - "./mirth-connect/custom-lib:/home/$USER/customlib2/:rw"
     # - "./data/spools/:/var/spool/mirth/:rw"
    ports: 
      - "8080:8080"
      - "8443:8443"      
      - "8902:5001"
      - "5100:5100"
      - "7011:7011"
      - "8092:8092"
      - "8181:8181"
      - "8182:8182"
      - "8093:8193"
      - "32768:32768"
      - "32772:32772" 
      - "32811:32811"
      - "5001:5001"
      - "7010:7010"
      - "7012:7012"
   

  
